# ============================================
# Namespace para QA
# ============================================
apiVersion: v1
kind: Namespace
metadata:
  name: notes-app-qa
  labels:
    app.kubernetes.io/name: notes-app
    environment: qa
